### PR TITLE
Fix for 2 new bugs and some improvements

### PR DESCRIPTION
**Pull request by herenyi**
Fix for a new bug (InstrumentationBug1Test).
Renamed most GithubIssue tests to be executed as unit tests and fixed closing the err and out streams at the end of the tests
Updated a deprecated function call.
Added back a fix to Java1.1.jj, which was accidentally removed before, but the GithubIssue53 test showed the problem again

### CODE REVIEW

**Comment by mtrovo** [comment]
A little bit off topic but...

Hey @herenyi I saw that you forked and commited some changes to the javancss project, adding support for java 8 syntax, are you planning to release this code on maven or something? 

#176 is a really old bug on this project and would benefit from a new release of javancss as the original maintainer seems to have abandoned the project.

**Comment by CsatariGergely** [comment]
@mtrovo  do you know what are our chances for a new Conbertura release?

**Comment by mtrovo** [comment]
Hi @CsatariGergely, I've been trying to talk to the core maintainers for a while and now it seems to be getting some traction, I hope we can see a new release in the coming months.

**Comment by herenyi** [comment]
I have added a fix to javancss to parse properly this: Runnable runnable = (Runnable)() -> System.out.println(\"Test\");

**Comment by CsatariGergely** [comment]
@

> 
> 
> Hi @CsatariGergely, I've been trying to talk to the core maintainers for a while and now it seems to be getting some traction, I hope we can see a new release in the coming months.

@mtrovo Thanks for the update.

**Comment by jmrozanec** [comment]
@herenyi @mtrovo @CsatariGergely @lewijw thank you for contributing to Cobertura! Special thanks to @mtrovo who reached out to us to move forward! 😄

**Comment by WolfgangFahl** [comment]
Any ETA?

**Pull request merged**
