### PR TITLE
 #379 Try with resources - net.sourceforge.cobertura.javancss.parser.…

### PR DESCRIPTION
**Pull request by msiemczyk**
…ParseException: Encountered " ")" ") ""

Try resource block can have semicolon at the end of variable definition and not have another variable. Java compiler will allow one additional semicolon, but Cobertura throws exception because that code was broken when update for Java 7 was made.

https://github.com/cobertura/cobertura/issues/379

I few additional changes I didn't really mean to, but you can skip those during the merge if you want.

### CODE REVIEW

**Comment by msiemczyk** [comment]
Travis build was successful with my changes.

https://travis-ci.org/msiemczyk/cobertura/builds/405387073

**Comment by herenyi** [comment]
I have also fixed the ; problem with the try with resource in my pull request. Also in the javancss project. It's nice to see some action around the project. It would be nice to have a new version too... :)

**Comment by msiemczyk** [comment]
Thanks @herenyi

**Comment by jmrozanec** [comment]
@msiemczyk @herenyi @lewijw @dennisl thank you for contributing to Cobertura! 😄

**Pull request merged**
