### PR TITLE
Line ending of .sh scripts and fix getting script directory

### PR DESCRIPTION
**Pull request by bdc34**
The .sh executables didn't work well and it seemed like they were trying to pick up the script directory. Fixed to use BASH_SOURCE and changed from DOS to Unix line endings.

### CODE REVIEW

**Comment by cobexer** [comment]
Why is this not merged and a new release published yet?

I just tried to add cobertura to my CI and hit "Error: Could not find or load main class net.sourceforge.cobertura.instrument.InstrumentMain" which this should fix (as far as my Google fu told me).
Anything holding this up?

**Comment by dalvizu** [comment]
@cobexer  - I'm not the maintainer, but to use this today what you can do is check out the `bdc34:master` repo / branch, build it locally as a new version (2.1.2.cobexer or whatever), and use that in your project

**Comment by cobexer** [comment]
@dalvizu That would require setting up an environment and figuring out how cobertura is built,... (I didn't even look :) ). instead I patched the files in the archive manually.

My comment was more about adding the specific error message here (to enable others to find the fix easier) and to figure out why a small fix like this is not yet merged after 5 months...

Calling dos2unix for all the .sh files resolved this issue for me btw. thus one more up-vote for merging this ;)

**Comment by cobexer** [comment]
Also all the $* must be replaced by "$@" (with quotes). See: https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html

**Comment by jmrozanec** [comment]
@bdc34 thank you for contributing to Cobertura! Also thanks to @cobexer and @jakecobb for observations regarding this PR! 😄

**Pull request merged**
