### PR TITLE
Fixes failing test cases and adds Java8 Lambdas and method references

### PR DESCRIPTION
**Pull request by herenyi**
1. Fixed test problems by updating dependencies, deperacated APIs
2. Updated latest javancss
3. Added lambda and method references to the parser to support Java8

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@christ66 Can you please take a look on this?

**Comment by christ66** [comment]
I'm still reviewing this, but there's a lot of unnecessary formatting changes which makes this review really difficult (even with `w=1`).

**Comment by jmrozanec** [comment]
@christ66 need some help reviewing this? may I jump in for some help?

**Comment by herenyi** [comment]
Maybe you can review them commit by commit, I have tried to separate things in such a way that only one change is in one commit and no formatting changes.

The main formatting changes are from the new version of the javancss merge. I think it should have the formatting of the original javancss for the future to be able to see if there are fixes there how to add it to cobertura. 

The other changes should be fairly small. 

Let me know if there are any questions.

**Comment by christ66** [comment]
Thank you @herenyi for this PR!

**Comment by herenyi** [comment]
You are welcome. Is there a chance to trigger the travis-ci build too, in theory it should be green this time. And also is it possible have a new 2.1.2 version from this build and continue the snapshot with 2.1.3-SNAPSHOT? It would help me to create an updated covertura maven plugin as well with this cobertura version.

**Comment by msiemczyk** [comment]
I agree, can we cut a release so I don't need my own version? I see that the build failed with test failures.

**Comment by christ66** [comment]
A release will be made this weekend

**Comment by christ66** [comment]
I'm not sure what happened to the ci build. I will re-add it tonight.

**Comment by herenyi** [comment]
Hi, Could you do the release and check the CI, please? Or if you don't have time I'm happy to help if I can. Cheers, Gergo

**Comment by msiemczyk** [comment]
@christ66 @jmrozanec Hey, I don't really know how Travis CI builds work, but is there anything I can do to help with the build part?

**Comment by msiemczyk** [comment]
I just pulled all these changed into my fork and now in one of our projects I get two new warnings:

`[INFO] Cobertura 2.1.2-SNAPSHOT - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[cobertura] |-INFO in CoverageDataFileHandler - Cobertura: Loaded information on 210 classes.
[cobertura] |-WARN in ComplexityCalculator - JavaNCSS got an error while parsing the java file ...\service\GspsObjectRouterService.java
ParseException in STDIN
Last useful checkpoint: "...service.GspsObjectRouterService.backfillRouteGspsItemsForStudy(String)"
Encountered " ")" ") "" at line 149, column 51.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    

[cobertura] |-WARN in ComplexityCalculator - JavaNCSS got an error while parsing the java file ...\service\ImpaxVoiceClipImporterService.java
ParseException in STDIN
Last useful checkpoint: "...service.ImpaxVoiceClipImporterService.WorkerThread.processBatch(WorkItem)"
Encountered " ")" ") "" at line 352, column 116.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    

Report time: 878ms`

**Comment by msiemczyk** [comment]
The first warning seems to be pointing to semicolon on the second PreparedStatement of try with resources, which is valid Java.

image

**Comment by msiemczyk** [comment]
Turns out that is an existing bug that is in the code already since Java 7 update, I can just see additional warning now with all the logging changes. The culprit is TryWithResources() in Java1.1.jj file.

**Comment by herenyi** [comment]
I have added a fix for the parsing error try with resource problem, there is a pending pull request for it.

**Pull request merged**
