### PR TITLE
Fix Java8 instrumentation exception due to use of ASM4 API version.

### LINKED ISSUE #248: INVOKESPECIAL/STATIC on interfaces require ASM 5
Using Cobertura 2.1.1 through Maven plugin 2.7, I get this exception:

    Unable to instrument file C:\Pro...\Lambdas.class
    java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
    at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]

The involved class is very small:

```java
/*
 * Copyright (C) 2015 Luciano Vernaschi <luciano at cromoteca.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.cromoteca.bfts.util;

import java.io.IOException;
import java.util.Comparator;
import java.util.function.Function;
import java.util.stream.Stream;

import static java.util.Comparator.*;
import static java.util.Objects.*;

/**
 * Utilities for lambda expressions
 *
 * @author Luciano Vernaschi <luciano at cromoteca.com>
 */
public class Lambdas {
  private Lambdas() {}

  /**
   * Consumes a stream without having to rethrow IOExceptions as
   * RuntimeExceptions. It uses Stream.forEachOrdered since we need the
   * happens-before contract to be sure that elements that follow an IOException
   * are not processed.
   */
  public static <T> void consumeIO(Stream<T> stream, IOConsumer<T> consumer)
      throws IOException {
    Container<IOException> ioex = new Container<>();

    stream.forEachOrdered(p -> {
      if (ioex.o == null) {
        try {
          consumer.accept(p);
        } catch (IOException ex) {
          ioex.o = ex;
        }
      }
    });

    if (ioex.o != null) {
      throw ioex.o;
    }
  }

  public interface IOConsumer<T> {
    void accept(T t) throws IOException;
  }

  /**
   * Allows to set and retrieve a single object. Used to set and retrieve an
   * object while in a lambda exception (can't set the object directly because
   * it must be effectively final to be used in the lambda body).
   */
  public static class Container<T> {
    public T o;
  }

  /**
   * Used in lambda expressions to sort according to a method of the stream
   * member class. For example, to sort a list of paths by file name, you can
   * write:
   *
   * <pre>paths.sorted(orderBy(Path::getFileName))</pre>
   */
  public static <T, R extends Comparable> Comparator<T> orderBy(Function<T, R> f) {
    return (o1, o2) -> compare(f.apply(o1), f.apply(o2), naturalOrder());
  }
}
```

Test class follows:

```java
package com.cromoteca.bfts.util;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Stream;
import org.junit.Test;

import static com.cromoteca.bfts.util.Lambdas.*;
import static org.junit.Assert.*;

public class LambdasTest {
  private static final String PARIS = "Paris";
  private static final String BERLIN = "Berlin";
  private static final String ROMA = "Roma";

  Stream<String> stream
      = Arrays.<String>stream(new String[] { ROMA, BERLIN, PARIS });

  @Test(expected = IOException.class)
  public void testConsumeIOWithoutComparator() throws Exception {
    Lambdas.<String>consumeIO(stream, s -> {
      switch (s) {
        case ROMA:
          break;
        case BERLIN:
          throw new IOException(BERLIN);
        case PARIS:
          fail("IOException should have happened before");
          break;
      }
    });
  }

  @Test(expected = IOException.class)
  public void testConsumeIOWithComparator() throws Exception {
    Lambdas.<String>consumeIO(stream.sorted(String::compareTo), s -> {
      switch (s) {
        case BERLIN:
          break;
        case PARIS:
          throw new IOException(PARIS);
        case ROMA:
          fail("IOException should have happened before");
      }
    });
  }

  @Test
  public void testSort() {
    String[] array = stream.sorted(orderBy(String::length)).toArray(String[]::new);
    assertEquals(ROMA, array[0]);
    assertEquals(PARIS, array[1]);
    assertEquals(BERLIN, array[2]);
  }
}
```
My environment is: jdk1.8.0_40 32 bit on Windows 7 x64, NetBeans 8.

I've just added Cobertura to my project, so the POM configuration is still very basic:

```xml
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
    </plugins>
  </reporting>
```

### PR DESCRIPTION
**Pull request by vkovalchuk**
Fix  #248 exception at instrumentation phase. No special handling logic for new API version is needed.

### CODE REVIEW

**Comment by Saiftari** [comment]
@christ66 : When this fix gonna be release? Please confirm.

**Comment by aaime** [comment]
Yep, a release would be much welcomed, right now cannot do coveage checks (well, one can use jacoco as an alternative, but I'd rather not, it's more invasive than cobertura build wise).

**Comment by christ66** [comment]
A release will be done soon (probably next weekend). I would like to write more java 8 specific unit tests to make sure there is no issues with java 8.

**Comment by Tournemine** [comment]
I'm also awaiting the new build like a child on a 24/12.

**Comment by Saiftari** [comment]
@christ66 : Can you give me the latest release version to pull and see if it works?

**Comment by RDevet** [comment]
We need a release, please!

**Comment by heidensi** [comment]
a release would be cool, yeah. :)

**Comment by jochenvdv** [comment]
+1

**Comment by erfangc** [comment]
the maven plugin need to be updated to reflect `2.1.2` as most people use **cobertura** via maven, currently even in **2.8-SNAPSHOT** the maven plugin is still pointing to `2.1.1` https://github.com/mojohaus/cobertura-maven-plugin/blob/master/pom.xml#L135

**Comment by cverges-medallia** [comment]
The plugin cannot be updated until a cobertura-runtime release for 2.1.2 is pushed to Maven Central.  Do we have an ETA for that?

**Comment by vrcca** [comment]
Is there an ETA for the 2.1.2 release already?

**Comment by xylo** [comment]
Did I miss something?  We are still waiting for a new release (2.1.2), although the bug was fixed half a year ago?  Is there any useful workaround or is this project dead?

**Comment by marioluan** [comment]
Is there an ETA for the 2.1.2 release already?

**Comment by tldavies** [comment]
2.1.2 being released anytime soon? This is breaking us from using cobertura.

**Comment by xylo** [comment]
Since this fix has been merged on 14 Mar 2016 I wonder if the fixed version (2.1.2) will be still released in 2018?  What is actually cobertura's release cycle for bug fix releases?  2, 5, or 10 years?

**Comment by codejayant** [comment]
I am stuck with the same issue. Seems new release will fix this issue. Anyone working to release a new version?

**Comment by VicZhang1** [comment]
Me too, can anyone release a new version? The latest version `2.1.1` is released in 2015.

**Comment by jmrozanec** [comment]
Hi everyone! We can release within two weeks. A snapshot release was issued a few months ago. Best!

**Comment by codejayant** [comment]
Hi @jmrozanec, can you please let us know when the new release is coming up? Also can you please share the snapshot release detail and if it has the fix?

**Comment by codejayant** [comment]
Hi, any latest development on this request?

**Comment by binarywang** [comment]
what happened? still no news?

**Pull request merged**
